# .github/workflows/publish-release.yml
name: Publish release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-permission:
    name: check permission
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: shogo82148/actions-check-permissions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    needs:
      - check-permission
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git for GitHub Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag using git-cliff
        id: bump_version
        run: |
          # Extract the version from the tag name (e.g., refs/tags/v1.2.3 -> 1.2.3)
          version="${GITHUB_REF#refs/tags/v}"
          echo "Current version is $version"
          # Create a VERSION file to track the version
          echo $version > VERSION
          git add VERSION
          git commit -m "chore: bump version to $version"
          git push origin main

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff-changelog
        with:
          config: cliff.toml
          args: --strip header
          output: CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff-release
        with:
          config: cliff.toml
          args: --latest --strip header
          output: RELEASE.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit CHANGELOG.md update
        run: |
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG for version $version"
          git branch -m main
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE.md
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up RELEASE.md
        run: |
          rm RELEASE.md
