default_language_version:
  python: python3.12

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
        exclude: |
          ^\.github/.*$|^mkdocs\.yml$
      - id: check-toml
        exclude: .github/
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        types: [python, pyi, jupyter]

      - id: ruff-format
        types: [python, pyi, jupyter]
        language: system

  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: python -m mypy
  #       exclude: |
  #         ^tests/|
  #       types: [python]
  #       args: [--strict]
  #       language: system
