name: ci

on:
  push:
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"
  PYTHON_VERSIONS: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-project:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.python-version == '3.13'}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "dev@pawamoy.fr"
        git config --global user.name "Timothée Mazzucotelli"
  
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        version: 'latest'
    
    - name: Pin python-version ${{ matrix.python-version }}
      run: rye pin ${{ matrix.python-version }}

    - name: Install Copier and rye
      run: rye sync

    - name: Test project generation and workflow
      run: bash tests/test_project.sh
